services:
  spark:
    version: 3.0.0
  hdfs:
    version: 2.7.3

provider: ec2

providers:
  ec2:
    key-name: oxclo01
    identity-file: /home/oxclo/keys/oxclo01.pem
    instance-type: m3.large
    region: eu-west-1
    ami: ami-0ea3405d2d2522162   # Amazon Linux 2, eu-west-1
    user: ec2-user
    instance-profile-name: ec2-access-s3

launch:
  num-slaves: 2
  install-hdfs: False