services:
  spark:
    version: 2.2.0
    download-source: "http://d3kbcqa49mib13.cloudfront.net/spark-2.2.0-bin-hadoop2.7.tgz"
  hdfs:
    version: 2.7.3

provider: ec2

providers:
  ec2:
    key-name: oxcloXX
    identity-file: /home/oxclo/keys/oxcloXX.pem
    instance-type: m3.large
    region: eu-west-1
    ami: ami-d7b9a2b1   # Amazon Linux, eu-west-1
    user: ec2-user
    instance-profile-name: ec2-access-s3
#    tenancy: default  # default | dedicated
#    ebs-optimized: no  # yes | no
#    instance-initiated-shutdown-behavior: terminate  # terminate | stop

launch:
  num-slaves: 2
  install-hdfs: False
